"""create greeting

Revision ID: 2a12223f2c63
Revises: a8345e9d3bc9
Create Date: 2023-06-01 18:13:49.035172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a12223f2c63'
down_revision = 'a8345e9d3bc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('is_greeting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'is_greeting')
    # ### end Alembic commands ###
