"""added rebound

Revision ID: 5584423f965e
Revises: b5c99d7a5497
Create Date: 2023-05-29 04:55:21.017459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5584423f965e'
down_revision = 'b5c99d7a5497'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'username')
    # ### end Alembic commands ###
