"""create greeting

Revision ID: 8e5caa59b9d7
Revises: 2a12223f2c63
Create Date: 2023-06-01 18:38:35.165239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5caa59b9d7'
down_revision = '2a12223f2c63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('type_message', sa.String(), nullable=False))
    op.drop_column('texts', 'is_rebound')
    op.drop_column('texts', 'is_greeting')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('is_greeting', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('texts', sa.Column('is_rebound', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('texts', 'type_message')
    # ### end Alembic commands ###
