"""added rebound

Revision ID: b5c99d7a5497
Revises: d76ba1c1e57b
Create Date: 2023-05-28 20:01:32.234530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c99d7a5497'
down_revision = 'd76ba1c1e57b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('is_rebound', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'is_rebound')
    # ### end Alembic commands ###
