"""init db

Revision ID: f20c1172a184
Revises: f4bf7763fd75
Create Date: 2023-06-01 10:00:06.923484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20c1172a184'
down_revision = 'f4bf7763fd75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('add_datetime', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'add_datetime')
    # ### end Alembic commands ###
