"""added rebound

Revision ID: f9ef467cd9bf
Revises: 5584423f965e
Create Date: 2023-05-29 05:23:32.838554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ef467cd9bf'
down_revision = '5584423f965e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ticket_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'ticket_hash')
    # ### end Alembic commands ###
